# Generated by Django 5.1 on 2024-11-15 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=85)),
                ("slug", models.SlugField()),
                ("preparation_time", models.IntegerField()),
                (
                    "preparation_time_unit",
                    models.CharField(
                        choices=[("Minutos", "Minutos"), ("Horas", "Horas")],
                        max_length=65,
                    ),
                ),
                ("servings", models.IntegerField()),
                (
                    "servings_unit",
                    models.CharField(
                        choices=[
                            ("Porções", "Porções"),
                            ("Pessoas", "Pessoas"),
                            ("Pedaços", "Pedaços"),
                        ],
                        max_length=65,
                    ),
                ),
                ("preparation_steps", models.TextField()),
                ("preparation_steps_is_html", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "cover",
                    models.ImageField(
                        blank=True, default="", upload_to="receitas/covers/%Y/%m/%d/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="receitas.category",
                    ),
                ),
                ("tags", models.ManyToManyField(to="tag.tag")),
            ],
        ),
    ]
